# Chapter8 三次元画像解析

In [8]:
import numpy as np

## 4.1
次の回転行列$\bm{R}$の逆行列を求めよ.
$
\bm{R} = 
\begin{pmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{pmatrix}
$

$\bm{R}^{-1} = 
\begin{pmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{pmatrix} = \bm{R} $

In [11]:
R = np.array([
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 1],
])
R@R

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
# R exchange x and y
R @ np.array([1, 2, 3]).T

array([2, 1, 3])

## 4.2
次の座標変換行列$\bm{M}$の逆行列を求めよ.
$
\bm{M} = 
\begin{pmatrix}
0 & 1 & 0 & 1 \\
1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}
$

$
\bm{M}^{-1} = 
\begin{pmatrix}
0 & 1 & 0 & 0 \\
1 & 0 & 0 & -1 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}
$

In [26]:
M = np.array([
    [0, 1, 0, 1],
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
])
M_inv = np.linalg.inv(M)
M_inv

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## 4.3
練習問題4.2の行列$\bm{M}$が世界座標系からカメラ座標系への変換行列であるとき, 世界座標系におけるカメラの位置と, 世界座標系におけるカメラ光軸方向のベクトルを求めよ.

世界座標系$\bm{V_w}$, カメラ座標系$\bm{V_c}$とし, $\bar{\bm{V_c}}^{T} = \bm{M}\bar{\bm{V_w}}^{T}$.

世界座標系におけるカメラの位置: $(0, -1, 0)$

$
\bm{M}^{-1} \begin{pmatrix}
0 \\
0 \\
0 \\
1  
\end{pmatrix} = \begin{pmatrix}
0 \\
-1 \\
0 \\
1  
\end{pmatrix}
$

世界座標系におけるカメラ光軸方向のベクトル: $(0, 0, 1)$

$
\bm{M}^{-1} \begin{pmatrix}
0 \\
0 \\
1 \\
0  
\end{pmatrix} = \begin{pmatrix}
0 \\
0 \\
1 \\
0  
\end{pmatrix}
$

In [29]:
print(M_inv @ np.array([0, 0, 0, 1]).T)
print(M_inv @ np.array([0, 0, 1, 0]).T)

[ 0. -1.  0.  1.]
[0. 0. 1. 0.]


## 4.4
世界座標系からカメラ座標系への変換行列$\bm{M}$が与えられたとする. このとき,世界座標系の三次元点$(100, 200, 300)$に対応する投影座標$(u, v)$を透視投影モデルを用いて計算せよ.
$
\bm{M} = 
\begin{pmatrix} 
0 & -1 & 0 & 100 \\
1 & 0 & 0 & 0 \\
0 & 0 & 1 & -200 \\
0 & 0 & 0 & 1 
\end{pmatrix}
$

In [25]:
M = np.array([
    [0, -1, 0, 100],
    [1, 0, 0, 0],
    [0, 0, 1, -200],
    [0, 0, 0, 1]
])
V_w = np.array([100, 200, 300])
V_c_bar = M @ np.append(V_w, 1).T
V_c = V_c_bar[:3]


u = V_c[0] / V_c[2]
v = V_c[1] / V_c[2]
(u, v)

(-1.0, 1.0)

## 4.5
カメラ内部パラメータ行列$\bm{A}$が次にように与えられたとする. 練習問題4.4で求めた投影座標$(u, v)$を画像座標$(m, n)$に変換せよ.
$
\bm{A} = 
\begin{pmatrix} 
100 & 0 & 320 & 0 \\
0 & 100 & 240 & 0 \\
0 & 0 & 1 & 0 
\end{pmatrix}
$

In [32]:
A = np.array([
    [100, 0, 320, 0],
    [0, 100, 240, 0],
    [0, 0, 1, 0]
])

(m, n, _) = A @ np.array([u, v, 1, 1]).T
(m, n)

(220.0, 340.0)